# Generated by Django 5.0.14 on 2026-08-08 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Normalized email address', max_length=254)),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the 6-digit OTP. Never store plaintext.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expires 5 minutes after creation')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts (max 5)')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP was successfully verified')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when a new OTP is generated or this one is used')),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_active'], name='accounts_em_email_f8617f_idx')],
            },
        ),
    ]
