# Generated by Django 5.0.14 on 2026-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='pending_name',
            field=models.CharField(blank=True, default='', help_text='Full name from registration form, stored until OTP is verified', max_length=150),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='pending_password_hash',
            field=models.CharField(blank=True, default='', help_text='Django password hash (NOT plaintext), stored until OTP is verified', max_length=128),
        ),
    ]
